### ISSUE TITLE
Patching cancelled...

### ISSUE THREAD

**Issue by PFAhard** [gaasedelen/patching#10]
Patching cancelled... when try to apply

**Comment by Kein** [comment]
Install properly as a user-plugin. Dont mix with other keystone stuff

**Comment by Slluxx** [comment]
@Kein What does that mean? i just installed it as given by the instructions 

eg `import urllib.request as r; exec(r.urlopen('https://github.com/gaasedelen/patching/raw/main/install.py').read())
`

**Comment by Kein** [comment]
`c:\Users\%USER%\AppData\Roaming\Hex-Rays\IDA Pro\plugins\`

**Comment by Slluxx** [comment]
Yes, i know where the plugins folder is.
There is nothing in it besides the patching plugin.

**Comment by Slluxx** [comment]
I managed to fix it by installing PyQt5 via pip and moving the file `D:\Program Files\Python311\Lib\site-packages\PyQt5\sip.cp311-win_amd64.pyd` to `E:\Programs\IDA Pro 7.6\python\3\PyQt5\sip.pyd`

Then i commented out line 32 (self.setWindowFlags) in `patching\ui\save_ui.py`

**Comment by ngokmink** [comment]
> I managed to fix it by installing PyQt5 via pip and moving the file `D:\Program Files\Python311\Lib\site-packages\PyQt5\sip.cp311-win_amd64.pyd` to `E:\Programs\IDA Pro 7.6\python\3\PyQt5\sip.pyd`
 
 This fixed both the "Assemble" crashing and "Patching cancelled" issue for me. Thank you.

**Comment by DragonQuestHero** [comment]
> I managed to fix it by installing PyQt5 via pip and moving the file `D:\Program Files\Python311\Lib\site-packages\PyQt5\sip.cp311-win_amd64.pyd` to `E:\Programs\IDA Pro 7.6\python\3\PyQt5\sip.pyd`
> 
> Then i commented out line 32 (`self.setWindowFlags`) in `patching\ui\save_ui.py`
> 
> To fix an IDA crashing when clicking on "Assemble...", i commented out line 42 (`self._line_assembly.setFocus`) in `patching\ui\preview_ui.py`
> 
> IDA Pro 7.6, Python 3.11, PyQt5==5.15.9

thinks+1

**Comment by gaasedelen** [comment]
Older versions of IDA don't like newer versions of Python. I see 3.11 references above.

Python 3.11 wasn't [officially supported](https://hex-rays.com/products/ida/news/8_2sp1/) by IDA until 8.2 SP1

I added a warning to the auto-install script to prevent installation for incompatible setups. If people want to bodge around it, they are welcome to but not something I am going to support.

Thanks for the report and hopefully people have found the context/discussion within this issue as helpful.
