### ISSUE TITLE
idasm is A Python Assembler Script Tool for IDA Pro based on "patching"

### ISSUE THREAD

**Issue by lyciumlee** [gaasedelen/patching#14]
Dear gaasedelen,
     I extract core codes from your ingenious "patching" plugin. Now we can use "patching" as an automatic patching work engine for IDA. Here is the repository link: https://github.com/lyciumlee/idasm .

**Comment by gaasedelen** [comment]
You should be able to script actions using the existing plugin core. I consciously exposed it to the IDA console but I guess I didn't technically document it:

https://github.com/gaasedelen/patching/blob/5a8c62156e9aa0260d915fe946e423b97971b841/plugins/patching.py#L82-L88

This shows how you can access or call into the core API:

![image](https://user-images.githubusercontent.com/9522648/182461057-f1a822e7-ef2d-4be5-b3ea-82f0164eda1e.png)

Any of the core API's I created and built the UI / actions on top of can be used for headless scripting / automation:

https://github.com/gaasedelen/patching/blob/main/plugins/patching/core.py#L292-L575

**Comment by lyciumlee** [comment]
Awesome!
