### ISSUE TITLE
problem with assemble

### ISSUE THREAD

**Issue by mishavac** [gaasedelen/patching#15]
when i try to use assemble i get error
 
![изображение](https://user-images.githubusercontent.com/106552893/205524870-e4f573d8-f18b-497e-85e7-5621a472463c.png)
i try on ida 7.6 and 7.7 and get some error
OC-widows10
executable file-arm64 dylib
if you need i can give .dmp file

**Comment by decuple-dream** [comment]
Same 🫥 IDA 7.7 ON ARM windows

**Comment by cyblpt** [comment]
i am this stage as well, i just fixed a problem and now i got this one, also using Ida Pro 7.7 but i tried in 7.6 and the same thing happens.

**Comment by VilotStar** [comment]
Has anyone found a fix to this issue?

**Comment by w1redch4d** [comment]
Use python version 3.10.4 or lower to fix the problem

**Comment by aundro** [comment]
Indeed, this is likely the same issue as https://github.com/gaasedelen/patching/issues/16
