### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by Arcansel** [gaasedelen/patching#16]
I tried the easy install command and it gives me the error of "ModuleNotFoundError: No module named '_socket'", so i tried manually installing it by dragging and dropping the patching folder directly inside the ida pro plugins folder along with "patching.py", then i used the manual install command listed in the instructions to install this plugin, next i restarted ida pro to check it out but still doesnt show up when i righ click a function. I have the latest python version which i downloaded straight from the oficial website, i even upgraded the pip, setuptool, six and wheel just in case as i don't have any ideia what is needed or not but still nothing, tried it in both ida pro 7.6 and 7.7.

I am on windows 11 with latest updates, let me know if you need any more info, thanks.

**Comment by cyblpt** [comment]
Update:  I found out how to solve the previous problem by creating an environment variable PYTHONPATH with the python dlls directory. Now i have another problem, when i try to assemble any code, it crashes and creates a dump automatically. I tried opening it in windbg and found out this error but i have no clue what to make of it or how to solve it.

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffceddf1ade (sip+0x0000000000001ade)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000010
Attempt to read from address 0000000000000010

PROCESS_NAME:  ida64.exe

READ_ADDRESS:  0000000000000010 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.

EXCEPTION_CODE_STR:  c0000005

EXCEPTION_PARAMETER1:  0000000000000000

EXCEPTION_PARAMETER2:  0000000000000010

**Comment by aundro** [comment]
Hi @cyblpt!

The issue you managed to solve, is this one: https://github.com/python/cpython/issues/100320
The one that you have not yet managed to solve, is likely due to Python's internal structures layout changes, and should be solved with 8.2SP1 (to be released in the next few days.)

**Comment by cyblpt** [comment]
> Hi @cyblpt!
> 
> The issue you managed to solve, is this one: [python/cpython#100320](https://github.com/python/cpython/issues/100320) The one that you have not yet managed to solve, is likely due to Python's internal structures layout changes, and should be solved with 8.2SP1 (to be released in the next few days.)
> 
> In the meantime, unless you really have to be using 3.11, I would recommend switching to Python 3.10

Thanks for the reply, i see, i will try switching to python 3.10 then, thanks a lot for the help.
