### ISSUE TITLE
crush in ida pro 7.7

### ISSUE THREAD

**Issue by llxiaoyuan** [gaasedelen/patching#18]
when click this
![image](https://github.com/gaasedelen/patching/assets/36320938/a2709e19-29b0-45ed-b884-737219ed2c5a)
ida will crush

![image](https://github.com/gaasedelen/patching/assets/36320938/8f43ba72-c63b-48cc-9abb-619937f3eb5a)

**Comment by hexraise** [comment]
Same problem for me.

**Comment by tahaghafuri** [comment]
And Me Have This Problem

**Comment by llxiaoyuan** [comment]
use python 3.9 to fix

**Comment by tahaghafuri** [comment]
Worked On IDA Pro 8.3 With Python 3.11
