### ISSUE TITLE
Not working since IDA Pro 9.0

### ISSUE THREAD

**Issue by loqstrz** [gaasedelen/patching#24]
Hi, please port this amazing plugin so it works on the latest IDA Pro 9.0.

https://web.archive.org/web/20240810011600/https://out5.hex-rays.com/beta90_6ba923/idapython_porting_guide.md

**Comment by loqstrz** [comment]
The errors im receiving in the console are:

plugins/util/ida.py: "import ida_struct" No module named 'ida_struct'
plugins/patching/asm.py: from patching.util.ida import *
plugins/patching/core.py: from patching.asm import*
plugins/patching/__init__.py: from patching.core import PatchingCore
plugins/patching.py: import patching

**Comment by Hazuki-san** [comment]
I agreed. This plugin SHOULD be in IDA 9.0

**Comment by Alois44623** [comment]
yup, would really appreciate a port as well :c

**Comment by breaking153** [comment]
Well I fix it myself by reading the doc. :) you can check that
[https://github.com/breaking153/patching](url)

**Comment by ohyeah521** [comment]
@breaking153   测试发现修改arm指令后无法保存，随便修改j个NOP，然后 Edit-Patch Program- Applay patches to input file

```
Keypatch: attempting to modify "MOV R11, #0" at 0x15888 to "nop "
Keypatch: successfully patched 4 byte(s) at 0x15888 from [00 B0 A0 E3] to [00 F0 20 E3]
15889: has no file mapping (original: B0 patched: F0)...skipping...
1588A: has no file mapping (original: A0 patched: 20)...skipping...
Applied 0/2 patch(es)
```
[test.zip](https://github.com/user-attachments/files/17492149/test.zip)

**Comment by breaking153** [comment]
> @breaking153 测试发现修改arm指令后无法保存，随便修改j个NOP，然后 Edit-Patch Program- Applay patches to input file
> 
> ```
> Keypatch: attempting to modify "MOV R11, #0" at 0x15888 to "nop "
> Keypatch: successfully patched 4 byte(s) at 0x15888 from [00 B0 A0 E3] to [00 F0 20 E3]
> 15889: has no file mapping (original: B0 patched: F0)...skipping...
> 1588A: has no file mapping (original: A0 patched: 20)...skipping...
> Applied 0/2 patch(es)
> ```
> 
> [test.zip](https://github.com/user-attachments/files/17492149/test.zip)

这个不是插件的问题，是file mapping不匹配的问题，你直接通过change bytes也没办法保存的，会显示skipping，我用别的arm架构软件是可以apply的

**Comment by ohyeah521** [comment]
@breaking153  明白了，感谢

**Comment by loqstrz** [comment]
@breaking153 Nice! How long did it take you to port this?

**Comment by breaking153** [comment]
> @breaking153 Nice! How long did it take you to port this?

well. it takes me about 2 hours to port it while some API just change its module,it's won't take too long.

**Comment by ramanveerji** [comment]
> Well I fix it myself by reading the doc. :) you can check that https://github.com/breaking153/patching

how to install and use this?

**Comment by kidimbwi** [comment]
you will find installation instructions here: https://github.com/breaking153/patching#installation

**Comment by ramanveerji** [comment]
> you will find installation instructions here: https://github.com/breaking153/patching#installation

The cmd is same for installation.
I tried to use the breaking153 repo url in cmd and still it is not working.

**Comment by kidimbwi** [comment]
download a zip of the code, uzip it to a convenient location on your hard drive and copy the plugins folder to %appdata%\Hex-Rays\IDA Pro\

![Patching](https://github.com/user-attachments/assets/f42a83d4-62d0-4d3d-87c7-4df7159d2415)

**Comment by ramanveerji** [comment]
> download a zip of the code, uzip it to a convenient location on your hard drive and copy the plugins folder to %appdata%\Hex-Rays\IDA Pro\
> 
> ![Patching](https://github.com/user-attachments/assets/f42a83d4-62d0-4d3d-87c7-4df7159d2415)
> 
> 

Okay

**Comment by breaking153** [comment]
@ramanveerji  you can just unzip it into <IDA Pro>/Plugins/dir and it will work, no need to run the command of original repo :)

**Comment by ramanveerji** [comment]
> @ramanveerji  you can just unzip it into <IDA Pro>/Plugins/dir and it will work, no need to run the command of original repo :)

Thank you 😊🙏

**Comment by gaasedelen** [comment]
Hi guys -

For IDA 9 compatibility, you should try the develop branch. The develop branch contains several other fixes and tweaks:

- https://github.com/gaasedelen/patching/tree/develop

I also fixed an important keystone issue today, the artifacts are available below:

- https://github.com/gaasedelen/keystone/actions/runs/11990698719

I'll probably merge v0.2.0 onto master in the coming days, such that the one-liner / auto-install will be working as expected for IDA 9 users.

**Comment by gaasedelen** [comment]
Closing as everything has been merged onto master. 

You should (in theory) be able to update your installed plugin to latest on master the [one-liners](https://github.com/gaasedelen/patching?tab=readme-ov-file#easy-install) in the main README.
